### PR TITLE
Add Gradle support

### LINKED ISSUE #26: Support for Gradle
Support Gradle with reading the version from either build.gradle or gradle.properties.

It is a simple property and should be easy to get, but it can be stored in either build.gradle or gradle.properties

    version = 1.0

This tool worked on a gradle project, but only on master branch. For any release branch it output 0.0.1 if I used --same-release, and without --same-release I got an error:
failed to get new version strconv.ParseInt: parsing "51.2": invalid syntax

### PR DESCRIPTION
**Pull request by zachwhaley**
Closes #26

### CODE REVIEW

**Comment by DJViking** [comment]
It does not check gradle.properties. The version might be in there in stead of build.gradle

**Comment by DJViking** [comment]
To pass the semantic check
`feat: Add Gradle support #26`

**Comment by DJViking** [comment]
Calling for reviewers, so we can get this merged.
@rawlingsj 
@ccojocar 
@almerico

**Comment by DJViking** [comment]
Still some checks that are pending.
Are we waiting for those, or can this PR be merged?

**Comment by DJViking** [comment]
Do all reviewers need to approve?
This PR should have been merged by now.

**Comment by zachwhaley** [comment]
For those that want this functionality, see my fork https://github.com/zachwhaley/new-release-version

**Comment by DJViking** [comment]
Is it safe then to assume this project is dead?

**Comment by rawlingsj** [comment]
@DJViking @zachwhaley hi sorry missed the github notifications, I've moved the repo to a top level and we will be able to monitor notifications now.  Yes we'd love that contribution, I cant reopen the PR as the branch has gone but if you want to create a new PR we'll add that in.

**Comment by DJViking** [comment]
@zachwhaley has done some great refactoring of the code in his fork.

**Comment by rawlingsj** [comment]
great fancy a PR and we can merge the two @zachwhaley?

**Comment by rawlingsj** [comment]
sorry we missed the original PR, if you'd rather not raise a new PR I can take a look at the changes and port them across.  Happy either way.

**Comment by zachwhaley** [comment]
@rawlingsj We assumed the project was stagnant and forked it for our own company.  You are free to look at the code changes we made, but we'll be maintaining our own fork for the foreseeable future :) 

See https://github.com/trendmicro/new-release-version

**Comment by rawlingsj** [comment]
@zachwhaley ok cool - totally makes sense, if we look at it we could cherry-pick your changes and add you as a maintainer but totally grok you doing the work and happy as things are.

**Pull request closed without merging**
